### ISSUE TITLE
The label of animatePlaceholder is not displayed when the initialValue is different from null

### ISSUE THREAD

**Issue by yxmpy** [mamaral/MAFormViewController#10]
The label of animatePlaceholder is not displayed when the initialValue is different from null.

![ios simulator screen shot 8 6 2015 17 37 18](https://cloud.githubusercontent.com/assets/12804514/8046520/591c0018-0e05-11e5-8a88-50e1f55aaae9.png)
![ios simulator screen shot 8 6 2015 17 39 17](https://cloud.githubusercontent.com/assets/12804514/8046519/591649f2-0e05-11e5-8083-5b909ad1ce7b.png)

**Comment by mamaral** [comment]
What version of MAFormViewController are you using?

**Comment by yxmpy** [comment]
Do not worry, this has been corrected!
