### ISSUE TITLE
Only Using Portions

### ISSUE THREAD

**Issue by pleirosei** [mamaral/MAFormViewController#11]
How do I only use portions of this framework.  I need to create a UITableViewController with static cells, one of which must contain an UIImageView, which this framework does not support.

I've been trying to add this functionality only to the cells individually, as opposed to creating a new MAFormViewController instance first.  Is there a way to do this?

Thanks,

Sean

**Comment by mamaral** [comment]
Sounds like you'd want to use the `MATextFieldCell` class?

**Comment by pleirosei** [comment]
Thanks for responding.  I attempted to use the MATextFieldCell class for the cell, but I must not be using it properly.  Attempting to do it in Swift, but I'm sure I'm missing like one step.  I'm doing something like the following:

@IBOutlet weak var phoneField: MATextFieldCell!

phoneField = MATextFieldCell(fieldType: MATextFieldTypePhone, action: MATextFieldActionTypeDone, animatePlaceholder: true, actionHandler: nil)


What am I missing?

Sean

**Comment by pleirosei** [comment]
I am essentially getting a "Found nil when unwrapping optional value", at the following line:

phoneField.textfield.placeholder = "Phone Number"

**Comment by mamaral** [comment]
If I had to guess it would be a swift version issue - IIRC the swift implementation was written when swift was in beta... Swift has obviously gone through a number of changes since then and will probably need to be re-factored.

**Comment by pleirosei** [comment]
Hey Man,

I found your first repo for this framework, and noticed you had a Swift example on that repo.  I was able to successfully implement it using that example.  You should move that example to the main repo since it is not there.

Thank-you for your quick responses man.  I greatly appreciate it!

Sean
