### ISSUE TITLE
Custom Field Types

### ISSUE THREAD

**Issue by t2** [mamaral/MAFormViewController#5]
Not really any issue, would love to see a date field type MM/DD/YYYY or at least a way to add an UIControlEventEditingChanged event with formatter. Any plans to do this?

**Comment by mamaral** [comment]
Not a bad idea. I'll look into making this extensible. In the meantime you should be able to set yourself as the text field's delegate and implement your own custom delegate methods. LMK if you need assistance!

**Comment by t2** [comment]
I am using MAFormFields. I guess I need to move to using MATextFieldCells?

**Comment by mamaral** [comment]
Ahh, right. I'll get back to you, a bit late here today but I'll let you know hopefully ASAP.

**Comment by t2** [comment]
Great! Thanks!

**Comment by mamaral** [comment]
Check out https://github.com/mamaral/MAFormViewController/pull/6. That should be what you're looking for! I also updated the demo to include a date cell at the end of the form if you want to test it out.
